### ISSUE TITLE
Link compound words

### ISSUE THREAD

**Issue by QubitPi** [QubitPi/wilhelm-vocabulary#127]
```yaml
  - term: die Fähigkeit
    definition: the ability
    audio: https://upload.wikimedia.org/wikipedia/commons/4/49/De-F%C3%A4higkeit.ogg
    declension:
      - ["",         singular,  plural     ]
      - [nominative, Fähigkeit, Fähigkeiten]
      - [genitive,   Fähigkeit, Fähigkeiten]
      - [dative,     Fähigkeit, Fähigkeiten]
      - [accusative, Fähigkeit, Fähigkeiten]
  - term: die Vorstellung
    definition:
      - the idea
      - the image
      - the representation
      - the introduction
    audio: https://upload.wikimedia.org/wikipedia/commons/b/b5/De-Vorstellung.oga
    declension:
      - ["",         singular,    plural       ]
      - [nominative, Vorstellung, Vorstellungen]
      - [genitive,   Vorstellung, Vorstellungen]
      - [dative,     Vorstellung, Vorstellungen]
      - [accusative, Vorstellung, Vorstellungen]
  - term: Vorstellungsfähigkeit
    definition:
    audio: https://upload.wikimedia.org/wikipedia/commons/4/49/De-Vorstellungsf%C3%A4higkeit.ogg
    declension:
      - ["",         singular,              plural                 ]
      - [nominative, Vorstellungsfähigkeit, Vorstellungsfähigkeiten]
      - [genitive,   Vorstellungsfähigkeit, Vorstellungsfähigkeiten]
      - [dative,     Vorstellungsfähigkeit, Vorstellungsfähigkeiten]
      - [accusative, Vorstellungsfähigkeit, Vorstellungsfähigkeiten]
```
